### ISSUE TITLE
Overflow in ByteSlice

### ISSUE THREAD

**Issue by jasonmoo** [OneOfOne/go-utils#1]
Hi.  Neat utils lib.  Was reading the `ByteSlice` function and realized that by taking a pointer to a `SliceHeader`, having a size of `3*sizeof(uintptr)`, from a `StringHeader`, having a size of `2*sizeof(uintptr)`, the `Cap` is overflowed..  You can see here that it is not initialized:

https://play.golang.org/p/kAq2in_Ho6

**Comment by OneOfOne** [comment]
I'll check it out, thanks!

**Comment by OneOfOne** [comment]
Thanks for finding this bug, I need to go through this library again.

BTW, it caused memory corruption, check https://play.golang.org/p/243R2LWVQj

**Comment by jasonmoo** [comment]
Cool, no worries.
