### ISSUE TITLE
Is this a real spinlock?

### ISSUE THREAD

**Issue by straightdave** [OneOfOne/go-utils#4]
Should the Goroutine keeps doing something before trying to get lock periodically when it fails to get the lock, rather than giving up the processor time by calling `runtime.Gosched()?

**Comment by OneOfOne** [comment]
That haven't been updated in a long time, however when I wrote it, without the `Gosched`, the whole program would freeze.

Also most (all?) spinlock implementation does something similar. 

from https://locklessinc.com/articles/locks/:

```
static void spin_lock(spinlock *lock)
{
	while (1)
	{
		if (!xchg_32(lock, EBUSY)) return;
	
		while (*lock) cpu_relax(); <<<<<
	}
}
```
